// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZpb3C7CyS0ZNdwlZrU9Dl-59DDvCi7Vw',
    appId: '1:422358596647:web:a8e2667c9dbae1c750a202',
    messagingSenderId: '422358596647',
    projectId: 'ecommerce-32fc3',
    authDomain: 'ecommerce-32fc3.firebaseapp.com',
    storageBucket: 'ecommerce-32fc3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoUqsXiGCJrEfU17ezmtK2bG59hSpjZ7s',
    appId: '1:422358596647:android:30b4bdf863a4eb1250a202',
    messagingSenderId: '422358596647',
    projectId: 'ecommerce-32fc3',
    storageBucket: 'ecommerce-32fc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLkyaxtAfJlBvghlgCyFSn8cMaI3eeA4A',
    appId: '1:422358596647:ios:b2accc2f415825eb50a202',
    messagingSenderId: '422358596647',
    projectId: 'ecommerce-32fc3',
    storageBucket: 'ecommerce-32fc3.appspot.com',
    iosBundleId: 'com.moanbm123.ecommerce',
  );
}
